# Netlify Configuration
# This file configures deployment settings for Netlify

[build]
  # No build process needed - static site
  publish = "."

[build.environment]
  # Node version (not required for static site)
  NODE_VERSION = "18"

[[headers]]
  # Security headers for all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; script-src 'self'; connect-src 'self' https://api.openweathermap.org https://api.weatherbit.io https://api.open-meteo.com https://api.weather.gov; img-src 'self' data:; font-src 'self' https://cdnjs.cloudflare.com"

[[headers]]
  # Cache static assets
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  # SPA fallback (not needed for this static site, but good to have)
  from = "/*"
  to = "/index.html"
  status = 404